Cleanup -Wunused-but-set-variable in csrmbcs.cpp
Clang extended Wunused-but-set-variable warning for pre/post unary
operators since https://github.com/llvm/llvm-project/commit/460fc440ad8d.
This started to trigger a warning in the following code:
icu/source/i18n/csrmbcs.cpp:149:13: error: variable
'singleByteCharCount' set but not used.

This patch cleans up chromium's copy until the issue is resolved
in the upstream: https://unicode-org.atlassian.net/browse/ICU-21966