Fix asm_to_inline_asm.py for Python 3
This fixes the following error:

FAILED: gen/third_party/icu/icudtl_dat.cc
.../depot_tools/bootstrap-2@3_8_10_chromium_23_bin/python3/bin/python3.exe ../../../v8/third_party/icu/scripts/asm_to_inline_asm.py gen/third_party/icu/icudtl_dat.S gen/th
ird_party/icu/icudtl_dat.cc
Traceback (most recent call last):
  File "../../../v8/third_party/icu/scripts/asm_to_inline_asm.py", line 31, in <module>
    sys.exit(asm_to_inl_asm(args.input, args.output))
  File "../../../v8/third_party/icu/scripts/asm_to_inline_asm.py", line 18, in asm_to_inl_asm
    outfile.write('__asm__(\n')
TypeError: a bytes-like object is required, not 'str'
[208/1882] ACTION //:run_torque(//build/toolchain/win:x64)
ninja: build stopped: subcommand failed.
Change-Id: Ic2b3f737ff234a836bfdc2101f1f85fc6d57e7d2