[build] Suppress -Wunused-but-set-variable
This patch suppresses -Wunused-but-set-variable warning
that icu code does not comply with.
The code that causes the warning is as the following:
third_party/icu/source/common/locid.cpp:300:17: error: variable 'size' set but not used.
int32_t size = 0;

Change-Id: Iac70e691baee9f7469a629a8cc0ed83eb4c9e065